project:
  type: book
  output-dir: docs
engine: knitr
filters:
  - Kangaa/glossary

book:
  title: "Logistic Regression with R"
  chapters:
    - index.qmd
    - ch_1_motivation.qmd
    - ch_2_introduction-to-logistic-regression.qmd
    - ch_3_fitting-logistic-regression-models.qmd
    - ch_4_assessing-model-fit.qmd
    - ch_5_predictions-from-logistic-regression-models.qmd
    - ch_6_extensions-case-study.qmd
    - glossary.qmd
  page-navigation: false
format:
  live-html:
    toc: true
    number-sections: true
    toc-depth: 2
    toc-expand: 3
    toc-title: Contents
    number-depth: 4

css:
 - include/webex.css
 - include/style.css
include-after-body:
 - include/webex.js
 - include/displayall.js
 - include/gating.js
 - include/skip-exercises.js
